version: "3"

networks:
  bot:

services:
  postgres:
    image: postgres:14-alpine3.15
    container_name: postgresql_ton
    tty: true
    restart: always
    volumes:
      - /var/lib/tonbot/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_DB: "$POSTGRES_DB"
    networks:
      - bot

  python:
    build:
      context: .
      dockerfile: Python.Dockerfile
    volumes:
      - ./:/home/tonconnector
    restart: always
    container_name: tonconnector
    networks:
      - bot

